title: Resume
url: "https://shaft101.github.io/"
baseurl: "/resume2"

markdown: kramdown
ins_logo: "./svnitlogo.png"

tracking_id: #

footer: yes
footer_url: "https://shaft101.github.io/resume2/"
footer_text: "Viraj Mohile"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/resume2/"
 - name: "Certifications"
   link: "certifications"
 - name: "Projects"
   link: "projects"
 - name: "Blog"
   link: "bloglist"
 - name: "Contact"
   link: "contact"

